site_name: SalesSense Docs
site_description: Simple docs to run SalesSense quickly
site_author: Cogent Infotech Innovation Lab

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Quick Start: quick-start.md
