[project]
name = "salessense"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.4.5",
    "openai>=1.99.9",
    "streamlit>=1.48.1",
]
